name: Build

on:
  pull_request:
    branches:
      - "main"
      - "develop"
      - "next"
      - "beta"
      - "alpha"
  push:
    branches:
      - "main"
      - "develop"
      - "next"
      - "beta"
      - "alpha"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: yarn
      - name: Installation
        run: yarn
        # run: yarn install --immutable # Fails if yarn.lock is modified (unfortunately only works for Yarn 2, and --frozen-lockfile is not the same!)
      - name: Check immutable yarn.lock
        run: git diff --exit-code
      - name: Test
        run: yarn test

  lint:
    name: Lint
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - name: Set up Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        with:
          node-version: "lts/*"
          cache: yarn
      - name: Installation
        run: yarn
        # run: yarn install --immutable # Fails if yarn.lock is modified (unfortunately only works for Yarn 2, and --frozen-lockfile is not the same!)
      - name: Check immutable yarn.lock
        run: git diff --exit-code
      - name: Lint
        run: yarn lint:ci

  commitlint:
    name: Commit Lint
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3
        with:
          node-version: "lts/*"
          cache: yarn
      - name: Installation
        run: yarn
        # run: yarn install --immutable # Fails if yarn.lock is modified (unfortunately only works for Yarn 2, and --frozen-lockfile is not the same!)
      - name: Check immutable yarn.lock
        run: git diff --exit-code
      - name: Commit Lint
        run: yarn lint:commit
